[build]
  command = "npm run dev"
  publish = "build"
  base = "server"  # Update to the correct path where server.js is located

[build.environment]
  NODE_VERSION = "22"
  PORT = "3000"
  MONGODB_URL = "mongodb+srv://rahulraw2002:86QzgS73eXe61PQ2@cluster0.s5p1x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

[functions]
  directory = "netlify-functions"
