[build]
  command = "npm run build"  # For front-end build
  publish = "build"

[functions]
  directory = "netlify-functions"  # Directory for Netlify Functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
