[build]
  command = "npm run dev"
  publish = "build"
  base = "server.js"
 

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301

[build.functions]
  directory = "netlify-functions"
